[tool.poetry]
name = "streaming-form-data"
version = "1.5.1"
description = "Streaming parser for multipart/form-data"
readme = "README.rst"
authors = ["Siddhant Goel <me@sgoel.org>"]
license = "MIT"
build = "build.py"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: Browsers",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    "Topic :: Internet :: WWW/HTTP :: HTTP Servers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3 :: Only",
]
include = ["LICENSE.txt"]
repository = "https://github.com/siddhantgoel/streaming-form-data"
documentation = "https://streaming-form-data.readthedocs.io/en/latest/"

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]
numpy = "^1.16"
pytest = "^4.4"
requests-toolbelt = "^0.9"
cython = "^0.29"
flake8 = "^3.7"
black = {version = "^18.3-alpha.0",allow-prereleases = true,python = "^3.6"}
mypy = "^0.720.0"

[tool.black]
line-length = 79
skip-string-normalization = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
